name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Docker Build
        uses: azure/docker-login@v1
        with:
          login-server: aidantpaymentgateway.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t aidantpaymentgateway.azurecr.io/payments-gateway:${{ github.sha }}
          docker push aidantpaymentgateway.azurecr.io/payments-gateway:${{ github.sha }}

      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          resource-group: payment-gateway
          dns-name-label: aidant-payment-gateway
          image: aidantpaymentgateway.azurecr.io/payments-gateway:${{ github.sha }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          name: payment-gateway-container
          location: 'north europe'
          restart-policy: Always
